import 'package:flutter_2048_program_language/src/model/dex.dart';

List<Dex> getDexData() {
  List<Dex> data = [
    Dex(
      id: 0,
      name: 'Bushy Boy',
      description: "",
      image: "mon01",
      value: 20,
      percent: .2,
    ),
    Dex(
      id: 1,
      name: 'Orc Orc',
      description: "",
      image: "mon02",
      value: 30,
      percent: .4,
    ),
    Dex(
      id: 2,
      name: 'Pinky Cyclops',
      description: "",
      image: "mon03",
      value: 40,
      percent: .6,
    ),
    Dex(
      id: 3,
      name: 'Bookworm',
      description: "",
      image: "mon04",
      value: 70,
      percent: .8,
    ),
    Dex(
      id: 4,
      name: 'Vampi',
      description: "",
      image: "mon05",
      value: 80,
      percent: 1,
    ),
    Dex(
      id: 5,
      name: 'Eater Ru Ru',
      description: "",
      image: "mon06",
      value: 90,
      percent: 1.2,
    ),
    Dex(
      id: 6,
      name: 'Athletoy',
      description: "",
      image: "mon07",
      value: 100,
      percent: 1.4,
    ),
    Dex(
      id: 7,
      name: 'Sand Lizard',
      description: "",
      image: "mon08",
      value: 120,
      percent: 1.6,
    ),
    Dex(
      id: 8,
      name: 'Green Frog',
      description: "",
      image: "mon09",
      value: 150,
      percent: 1.8,
    ),
    Dex(
      id: 9,
      name: 'Super Slow Zombie',
      description: "",
      image: "mon10",
      value: 170,
      percent: 2,
    ),
    Dex(
      id: 10,
      name: 'Clowny',
      description: "",
      image: "mon11",
      value: 200,
      percent: 2.2,
    ),
    Dex(
      id: 11,
      name: 'Billy & Terry',
      description: "",
      image: "mon12",
      value: 250,
      percent: 2.4,
    ),
    Dex(
      id: 12,
      name: 'Ruby Bunny',
      description: "",
      image: "mon13",
      value: 300,
      percent: 2.6,
    ),
    Dex(
      id: 13,
      name: 'Alien AB',
      description: "",
      image: "mon14",
      value: 350,
      percent: 2.8,
    ),
    Dex(
      id: 14,
      name: 'Heater',
      description: "",
      image: "mon15",
      value: 400,
      percent: 3,
    ),
    Dex(
      id: 15,
      name: 'Pumpkin Pancake',
      description: "",
      image: "mon16",
      value: 450,
      percent: 3.2,
    ),
    Dex(
      id: 16,
      name: 'Stonie',
      description: "",
      image: "mon17",
      value: 500,
      percent: 3.4,
    ),
    Dex(
      id: 17,
      name: 'Zason',
      description: "",
      image: "mon18",
      value: 550,
      percent: 3.6,
    ),
    Dex(
      id: 18,
      name: 'EX - 512',
      description: "",
      image: "mon19",
      value: 600,
      percent: 3.8,
    ),
    Dex(
      id: 19,
      name: 'Wash',
      description: "",
      image: "mon20",
      value: 650,
      percent: 4,
    ),
    Dex(
      id: 20,
      name: 'Blue Bolt',
      description: "",
      image: "mon21",
      value: 700,
      percent: 4.2,
    ),
    Dex(
      id: 21,
      name: 'Monkey King',
      description: "",
      image: "mon22",
      value: 750,
      percent: 4.4,
    ),
    Dex(
      id: 22,
      name: 'The Galaxy',
      description: "",
      image: "mon23",
      value: 800,
      percent: 4.6,
    ),
    Dex(
      id: 23,
      name: 'Atem',
      description: "",
      image: "mon24",
      value: 1000,
      percent: 5.0,
    ),
  ];
  return data;
}
