import 'package:flutter_2048_program_language/src/model/monster_item.dart';

List<Monsters_Items> getItemData() {
  List<Monsters_Items> data = [
    Monsters_Items(
        id: 1,
        name: "Bushy's Shiny Rock",
        description: "",
        image: "01",
        value: 500,
        isActive: false,
        point: 1),
    Monsters_Items(
        id: 2,
        name: "Bushy's Superhero Sticker",
        description: "",
        image: "02",
        value: 1000,
        isActive: false,
        point: 2),
    Monsters_Items(
        id: 3,
        name: "Bushy's Lucky Baseball",
        description: "",
        image: "03",
        value: 2000,
        isActive: false,
        point: 3),
    Monsters_Items(
        id: 4,
        name: "Orc's Broken Teeth",
        description: "",
        image: "04",
        value: 3000,
        isActive: false,
        point: 4),
    Monsters_Items(
        id: 5,
        name: "Orc's Ice Cream",
        description: "",
        image: "05",
        value: 4000,
        isActive: false,
        point: 5),
    Monsters_Items(
        id: 6,
        name: "Orc's Axe",
        description: "",
        image: "06",
        value: 5000,
        isActive: false,
        point: 6),
    Monsters_Items(
        id: 7,
        name: "Pinky's Hairpin",
        description: "",
        image: "07",
        value: 6000,
        isActive: false,
        point: 7),
    Monsters_Items(
        id: 8,
        name: "Pinky's Handbag",
        description: "",
        image: "08",
        value: 7000,
        isActive: false,
        point: 8),
    Monsters_Items(
        id: 9,
        name: "Pinky's Lipstick",
        description: "",
        image: "09",
        value: 8000,
        isActive: false,
        point: 9),
    Monsters_Items(
        id: 10,
        name: "Bookworn's Glasses",
        description: "",
        image: "10",
        value: 9000,
        isActive: false,
        point: 10),
    Monsters_Items(
        id: 11,
        name: "Bookworn's Wooden Sword",
        description: "",
        image: "11",
        value: 10000,
        isActive: false,
        point: 11),
    Monsters_Items(
        id: 12,
        name: "Bookworn's Treasue Map",
        description: "",
        image: "12",
        value: 12000,
        isActive: false,
        point: 12),
    Monsters_Items(
        id: 13,
        name: "Vampi's Cape",
        description: "",
        image: "13",
        value: 14000,
        isActive: false,
        point: 13),
    Monsters_Items(
        id: 14,
        name: "Vampi's Bat",
        description: "",
        image: "14",
        value: 16000,
        isActive: false,
        point: 14),
    Monsters_Items(
        id: 15,
        name: "Vampi's Blood Bag",
        description: "",
        image: "15",
        value: 18000,
        isActive: false,
        point: 15),
    Monsters_Items(
        id: 16,
        name: "RuRu's Mr.Worm",
        description: "",
        image: "16",
        value: 20000,
        isActive: false,
        point: 16),
    Monsters_Items(
        id: 16,
        name: "RuRu's Mystery Ticket",
        description: "",
        image: "17",
        value: 25000,
        isActive: false,
        point: 17),
    Monsters_Items(
        id: 17,
        name: "Athletoy's Smart Watch",
        description: "",
        image: "18",
        value: 30000,
        isActive: false,
        point: 18),
    Monsters_Items(
        id: 18,
        name: "Athletoy's Earphone",
        description: "",
        image: "19",
        value: 40000,
        isActive: false,
        point: 19),
    Monsters_Items(
        id: 18,
        name: "S.Lizard's Tail",
        description: "",
        image: "20",
        value: 50000,
        isActive: false,
        point: 20),
    Monsters_Items(
        id: 19,
        name: "Dream Artifact",
        description: "",
        image: "21",
        value: 75000,
        isActive: false,
        point: 25),
    Monsters_Items(
        id: 20,
        name: "Emotion Artifact",
        description: "",
        image: "22",
        value: 100000,
        isActive: false,
        point: 30),
  ];
  return data;
}
