import 'package:flutter_2048_program_language/src/utils/utils.dart';

class Puzzle {
  final int id;
  final List<int> map;
  final int step;
  final List<String> solve;
  final List<int> required;
  final List<int> required_value;
  final String image;

  Puzzle(
      {this.id,
      this.map,
      this.step,
      this.required,
      this.image,
      this.required_value,
      this.solve});
}

List<Puzzle> getListPuzzle() {
  List<Puzzle> data = [
    Puzzle(
      id: 0,
      map: [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        0
      ],
      solve: [down, left],
      step: 2,
      image: easy_img,
      required: [
        4,
      ],
      required_value: [
        1,
      ],
    ),
    Puzzle(
        id: 1,
        map: [
          0,
          0,
          0,
          2,
          2,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          2,
          2,
          0,
          0,
          0
        ],
        solve: [left],
        step: 1,
        image: easy_img,
        required: [
          4,
        ],
        required_value: [
          2,
        ]),
    Puzzle(
        id: 2,
        map: [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          2,
          2,
          2,
          2,
          0,
          2,
          2,
          2,
          2,
          0
        ],
        solve: [down, left, left],
        step: 3,
        image: easy_img,
        required: [
          16,
        ],
        required_value: [
          1,
        ]),
    Puzzle(
        id: 3,
        map: [
          4,
          0,
          4,
          0,
          4,
          0,
          0,
          0,
          0,
          0,
          4,
          0,
          4,
          0,
          4,
          0,
          0,
          0,
          0,
          0,
          8,
          0,
          8,
          0,
          8,
        ],
        solve: [up],
        step: 1,
        image: easy_img,
        required: [16],
        required_value: [
          3,
        ]),
    Puzzle(
        id: 4,
        map: [
          0,
          0,
          0,
          2,
          2,
          16,
          16,
          16,
          2,
          2,
          0,
          16,
          16,
          16,
          0,
          2,
          2,
          16,
          16,
          16,
          2,
          2,
          0,
          0,
          0
        ],
        solve: [down, right],
        step: 2,
        image: easy_img,
        required: [8],
        required_value: [
          2,
        ]),
    Puzzle(
        id: 5,
        map: [
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          0,
          2
        ],
        solve: [down, left, left],
        step: 3,
        image: easy_img,
        required: [16],
        required_value: [
          1,
        ]),
    Puzzle(
        id: 6,
        map: [
          128,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          8,
          0,
          0,
          0,
          0,
          0,
          4,
          2,
          0,
          0,
          0,
          2,
          2,
          64,
          256,
          128
        ],
        solve: [left, down],
        step: 2,
        image: normal_img,
        required: [16],
        required_value: [
          1,
        ]),
    Puzzle(
        id: 7,
        map: [
          2,
          2,
          64,
          128,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          32,
          16,
          0,
          0,
          0,
          0,
          0,
          0,
          32,
          2,
          2,
          32,
          256
        ],
        solve: [right, down],
        step: 2,
        image: normal_img,
        required: [8],
        required_value: [
          1,
        ]),
    Puzzle(
        id: 8,
        map: [
          0,
          0,
          4,
          64,
          1024,
          0,
          0,
          0,
          0,
          0,
          2,
          64,
          32,
          128,
          128,
          0,
          0,
          0,
          0,
          0,
          0,
          128,
          2,
          256,
          2
        ],
        solve: [left, up, left, up],
        step: 4,
        image: normal_img,
        required: [8],
        required_value: [
          1,
        ]),
    Puzzle(
        id: 9,
        map: [
          4,
          4,
          2048,
          4,
          4,
          4,
          4,
          512,
          4,
          4,
          4,
          4,
          512,
          4,
          4,
          4,
          4,
          512,
          4,
          4,
          4,
          4,
          512,
          4,
          4,
        ],
        solve: [up, up, down, left, left],
        step: 5,
        image: normal_img,
        required: [64],
        required_value: [
          1,
        ]),
    Puzzle(
        id: 10,
        map: [
          256,
          0,
          8,
          0,
          4,
          0,
          4,
          0,
          256,
          4,
          0,
          4,
          16,
          0,
          4,
          2048,
          0,
          512,
          0,
          128,
          1024,
          0,
          256,
          0,
          2048
        ],
        solve: [up, right, left, up],
        step: 4,
        image: normal_img,
        required: [32],
        required_value: [1]),
    Puzzle(
        id: 11,
        map: [
          2,
          2,
          1024,
          2,
          2,
          2,
          2,
          1024,
          2,
          2,
          4,
          4,
          2048,
          4,
          4,
          4,
          4,
          1024,
          4,
          4,
          8,
          8,
          2048,
          8,
          8
        ],
        solve: [down, down, right, up, left, down],
        step: 6,
        image: hard_img,
        required: [64],
        required_value: [1]),
    Puzzle(
        id: 12,
        map: [
          16,
          4,
          0,
          0,
          0,
          4,
          256,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          8,
          0,
          0,
          0,
          16,
          4,
          0,
          0,
          8,
          4,
          1024,
        ],
        solve: [left, up, right, down, left, down],
        step: 6,
        required: [64],
        image: hard_img,
        required_value: [1]),
    Puzzle(
        id: 13,
        map: [
          0,
          0,
          0,
          0,
          32,
          0,
          0,
          0,
          2048,
          0,
          4,
          4,
          8,
          8,
          16,
          0,
          0,
          512,
          2,
          256,
          0,
          0,
          0,
          1024,
          256
        ],
        solve: [right, right, up, left, down, right],
        step: 6,
        required: [64],
        image: hard_img,
        required_value: [1]),
    Puzzle(
        id: 14,
        map: [
          0,
          0,
          2,
          0,
          512,
          0,
          0,
          64,
          0,
          0,
          0,
          0,
          32,
          0,
          0,
          0,
          0,
          2,
          0,
          512,
          4,
          32,
          1024,
          32,
          8,
        ],
        solve: [right, down, left, up, right, down, up, left],
        step: 8,
        required: [128],
        image: hard_img,
        required_value: [1]),
    Puzzle(
        id: 15,
        map: [
          2,
          32,
          2,
          32,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          32,
          2,
          32,
          2,
          0,
          2,
          0,
          2,
          0,
          2,
          32,
          2,
          32,
          2
        ],
        solve: [down, left, up, right, down, up, left, down, right, down],
        step: 10,
        required: [16],
        image: master_img,
        required_value: [1]),
  ];
  return data;
}
